name: "ngrok SSH tunnel (macOS 14)"

on:
  workflow_dispatch:

jobs:
  ngrok_ssh_tunnel:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: "20.11.0"
      - name: Start SSH via ngrok
        run: ./start_ngrok_tunnel.sh
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          SSH_PUBLIC_KEY: ${{ secrets.NGROK_SSH_PUBLIC_KEY }}
        shell: bash
      - name: Keep tunnel alive for 24 hours
        run: sleep 86400
        shell: bash
